### ISSUE TITLE
sdist on PyPI doesn't contain data/*.npy

### ISSUE THREAD

**Issue by hoechenberger** [hbldh/lspopt#6]
### Description

In addition to the missing changelog (which I'm addressing in #5), the sdists on PyPI are also lacking `data/*.npy`, meaning the package cannot be imported after it's been installed.

**Comment by hbldh** [comment]
That was strange that I missed testing that last time I released it. Will fix when I have some time to spare.

But surely you can install the wheel instead? Or install directly from the Github repo?

**Comment by hoechenberger** [comment]
Hi! I was trying to package LSPOpt for conda-forge, and they require you to use an sdist 😅 this is how I discovered the problem.

**Comment by hbldh** [comment]
There, it should be fixed with version 1.2.0 now available on PyPI. I can successfully install from source dist and build wheels from it as well. Thank you for reporting it!

**Comment by hoechenberger** [comment]
Super cool, thank you!!
